project:
  title: "Slides"

editor: source

format: 
  revealjs:
    theme: [moon,CustomCL.scss]
    controls: true
    incremental: true
    slide-number: true
    preview-links: false
    footer: <a href="https://ai.lange-analytics.com" target="_blank">https://ai.lange-analytics.com/</a>
    code-fold: false